name: Test Helm Access

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: dev-cluster
  AWS_REGION: ap-south-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup kubectl and Helm
      uses: azure/setup-helm@v3

    - name: Test access
      run: |
        # Configure kubeconfig
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
        
        echo "=== Testing kubectl ==="
        kubectl get nodes
        
        echo "=== Testing Helm ==="
        helm version
        helm ls --all-namespaces || echo "No existing releases"
