name: Deploy Prometheus and Grafana

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CLUSTER_NAME: dev-cluster
  AWS_REGION: ap-south-1
  NAMESPACE: prometheus

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region ${{ env.AWS_REGION }} \
          --name ${{ env.CLUSTER_NAME }}

    - name: Check nodes
      run: |
        echo "=== Current Nodes ==="
        kubectl get nodes
        echo ""
        echo "If no nodes shown above, the deployment will fail."

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Deploy Monitoring Stack
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace ${{ env.NAMESPACE }} \
          --set server.service.type=LoadBalancer \
          --set server.persistentVolume.enabled=false

        helm upgrade --install grafana grafana/grafana \
          --namespace ${{ env.NAMESPACE }} \
          --set service.type=LoadBalancer \
          --set persistence.enabled=false \
          --set adminPassword=admin

    - name: Wait and display results
      run: |
        sleep 60
        echo "=== Deployment Status ==="
        kubectl get pods,svc -n ${{ env.NAMESPACE }}
        
        echo ""
        echo "=== LoadBalancer URLs ==="
        kubectl get svc -n ${{ env.NAMESPACE }} -o wide
