name: Debug AWS Access

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: dev-cluster
  AWS_REGION: ap-south-1

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Test AWS Credentials
      run: |
        echo "=== Testing AWS Credentials ==="
        aws sts get-caller-identity

    - name: Test EKS Access
      run: |
        echo "=== Testing EKS Cluster Access ==="
        aws eks list-clusters --region ${{ env.AWS_REGION }}
        aws eks describe-cluster --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} --query 'cluster.status'

    - name: Test kubectl
      run: |
        echo "=== Testing kubectl ==="
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
        kubectl get nodes
